# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-11 11:32
from __future__ import unicode_literals

from datetime import timedelta

from django.conf import settings
from django.db import migrations


def populate_expiry_date(apps, schema_editor):
    """
    Populate the field `expiry_date` for model SoftwareSecurePhotoVerification
    The function calculates the expiry date by adding DAYS_GOOD_FOR to field `updated_at`.

    We get the model SoftwareSecurePhotoVerification from the versioned app registry
    """
    SoftwareSecurePhotoVerification = apps.get_model('verify_student', 'SoftwareSecurePhotoVerification')
    software_secure_verifications = SoftwareSecurePhotoVerification.objects.filter(status='approved')

    for verification in software_secure_verifications:
        verification.expiry_date = verification.updated_at + timedelta(
            days=settings.VERIFY_STUDENT["DAYS_GOOD_FOR"]
        )
        verification.save()


def reverse_populate_expiry_date(apps, schema_editor):
    """
    Reverses the action taken by function `populate_expiry_date`

    The function populate_expiry_date() populates the expiry_date field
    and reverse_function() reverses that action i.e puts default value `NULL` back
    """
    SoftwareSecurePhotoVerification = apps.get_model('verify_student', 'SoftwareSecurePhotoVerification')
    software_secure_verifications = SoftwareSecurePhotoVerification.objects.filter(status='approved')

    for verifcation in software_secure_verifications:
        verifcation.expiry_date = None
        verifcation.save()


class Migration(migrations.Migration):

    dependencies = [
        ('verify_student', '0011_add_fields_to_sspv'),
    ]

    operations = [
        migrations.RunPython(populate_expiry_date, reverse_populate_expiry_date),
    ]
